### ISSUE TITLE
Proxy block information in debug-gts.py output

### ISSUE THREAD

**Issue by l-kent** [UQ-PAC/gtirb-semantics#4]
When there is an edge pointing to a proxy block, it would be helpful if the debug.gts.py output could include some further information about that proxy block if possible. I am unsure exactly how much information is associated with the proxy blocks, but it seems like if the proxy block is a proxy for an external call, the name of the external function being called can be retrieved at least, and that is information that would be helpful. If there is anything more than that that can be included, that would be great too.

**Comment by katrinafyi** [comment]
Walter has informed me that the relevant code is at https://github.com/UQ-PAC/bil-to-boogie-translator/blob/46a35d7abf884c8a91e9fef489a23b03b16fb230/src/main/scala/translating/GTIRBToIR.scala#L132. This follows the proxy block of PLT (?) functions to retrieve the actual symbol name.

This should handle most cases. Is there any more information you think would be useful?

**Comment by l-kent** [comment]
Yes, that's what prompted this. It would be helpful if that information was included in the .json output.

I don't know what other information is available in relation to the proxy blocks - what is there?

**Comment by katrinafyi** [comment]
It appears not much, they are largely dead ends in GTIRB's control flow.

**Comment by l-kent** [comment]
In that case, just marking the ones that we can tell are external calls and making it clear what they are an external call to would suffice.

**Comment by wnedov** [comment]
@l-kent 
I edited debug_gts so that the proxyblocks that are an external call now have the function name beside them. ProxyBlocks that aren't external calls I mark as unresolved. Tell me if there are any issues.
